// ---------------------------------------------------------------------------
// Generates src/data/assetManifest.js by scanning the processed + legacy
// character art in /public. The manifest lets <Character> render a <picture>
// with the exact set of files that actually exist for each id/variant WITHOUT
// probing the network at runtime — so the browser downloads exactly one format
// and size instead of every candidate.
//
// Run:  node scripts/gen_asset_manifest.mjs   (also wired as `npm run prebuild`)
// ---------------------------------------------------------------------------
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const pub = path.join(root, 'public')
const processedRoot = path.join(pub, 'characters-processed')
const legacyRoot = path.join(pub, 'characters')

const exists = (p) => fs.existsSync(p)

// ---- processed variants: { "<variant>/<stem>": {png1x,png2x,webp1x,webp2x} } --
const processed = {}
if (exists(processedRoot)) {
  for (const variant of fs.readdirSync(processedRoot)) {
    const dir = path.join(processedRoot, variant)
    if (!fs.statSync(dir).isDirectory()) continue
    // stems = base names of every *.png that is not an @2x file
    const stems = new Set()
    for (const f of fs.readdirSync(dir)) {
      const m = /^(.*)\.png$/.exec(f)
      if (m && !m[1].endsWith('@2x')) stems.add(m[1])
    }
    for (const stem of stems) {
      const rel = (suffix, ext) => `/characters-processed/${variant}/${stem}${suffix}.${ext}`
      const png1x = path.join(dir, `${stem}.png`)
      if (!exists(png1x)) continue
      processed[`${variant}/${stem}`] = {
        png1x: rel('', 'png'),
        png2x: exists(path.join(dir, `${stem}@2x.png`)) ? rel('@2x', 'png') : null,
        webp1x: exists(path.join(dir, `${stem}.webp`)) ? rel('', 'webp') : null,
        webp2x: exists(path.join(dir, `${stem}@2x.webp`)) ? rel('@2x', 'webp') : null,
      }
    }
  }
}

// ---- legacy flat art: { "<file>": "/characters/<file>" } --------------------
const legacy = {}
if (exists(legacyRoot)) {
  for (const f of fs.readdirSync(legacyRoot)) {
    if (/\.(png|webp|jpe?g)$/i.test(f)) legacy[f] = `/characters/${f}`
  }
}

const out = `// AUTO-GENERATED by scripts/gen_asset_manifest.mjs — do not edit by hand.
// Regenerate after adding/removing character art: node scripts/gen_asset_manifest.mjs
export const PROCESSED = ${JSON.stringify(processed, null, 2)}

export const LEGACY = ${JSON.stringify(legacy, null, 2)}
`

const dest = path.join(root, 'src', 'data', 'assetManifest.js')
fs.writeFileSync(dest, out)
console.log(`wrote ${path.relative(root, dest)} — ${Object.keys(processed).length} processed, ${Object.keys(legacy).length} legacy`)
